<a href="https://colab.research.google.com/github/adharshraj77/Adharsh_Portfolio/blob/main/FIFA_preprocessing_FeatureEngineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## FIFA

# Data Cleaning

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
# Remove row display limit
pd.set_option('display.max_rows', None)

In [ ]:
df  = pd.read_csv('/content/drive/MyDrive/players_20.csv')

In [ ]:
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

## Basic Discription of the data

In [ ]:
# Basic EDA and inspection of the FIFA 20 dataset
print("🔹 Shape of the dataset:")
print(df.shape)

print("\n🔹 Column names:")
print(df.columns.tolist())

print("\n🔹 Dataset info:")
df.info()

print("\n🔹 Statistical summary (numerical & categorical):")
display(df.describe(include='all').T)

print("\n🔹 Missing values count:")
print(df.isnull().sum().sort_values(ascending=False))

print("\n🔹 Number of duplicate rows:")
print(df.duplicated().sum())

print("\n🔹 First 5 rows of the dataset:")
display(df.head())

🔹 Shape of the dataset:
(18278, 104)

🔹 Column names:
['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club', 'overall', 'potential', 'value_eur', 'wage_eur', 'player_positions', 'preferred_foot', 'international_reputation', 'weak_foot', 'skill_moves', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'team_position', 'team_jersey_number', 'loaned_from', 'joined', 'contract_valid_until', 'nation_position', 'nation_jersey_number', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed', 'gk_positioning', 'player_traits', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb']

🔹 Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18278 entries, 0 to 18277
Columns: 104 entries, sofifa_id to rb
dtypes: float64(16), int64(45), object(43)
memory usage: 14.5+ MB

🔹 Statistical summary (numerical & categorical):

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
sofifa_id,18278.0,NaN,NaN,NaN,219738.864482,27960.200461,768.0,204445.5,226165.0,240795.75,252905.0
player_url,18278,18278,https://sofifa.com/player/233449/ximing-pan/20...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
short_name,18278,17354,J. Rodríguez,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
long_name,18278,18218,Liam Kelly,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,18278.0,NaN,NaN,NaN,25.283291,4.656964,16.0,22.0,25.0,29.0,42.0
dob,18278,6142,1992-02-29,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
height_cm,18278.0,NaN,NaN,NaN,181.362184,6.756961,156.0,177.0,181.0,186.0,205.0
weight_kg,18278.0,NaN,NaN,NaN,75.276343,7.047744,50.0,70.0,75.0,80.0,110.0
nationality,18278,162,England,1667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
club,18278,698,Wolverhampton Wanderers,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
overall,18278.0,NaN,NaN,NaN,66.244994,6.949953,48.0,62.0,66.0,71.0,94.0
potential,18278.0,NaN,NaN,NaN,71.546887,6.139669,49.0,67.0,71.0,75.0,95.0
value_eur,18278.0,NaN,NaN,NaN,2484037.64088,5585481.061474,0.0,325000.0,700000.0,2100000.0,105500000.0
wage_eur,18278.0,NaN,NaN,NaN,9456.942773,21351.714095,0.0,1000.0,3000.0,8000.0,565000.0
player_positions,18278,643,CB,2322,NaN,NaN,NaN,NaN,NaN,NaN,NaN
preferred_foot,18278,2,Right,13960,NaN,NaN,NaN,NaN,NaN,NaN,NaN
international_reputation,18278.0,NaN,NaN,NaN,1.103184,0.378861,1.0,1.0,1.0,1.0,5.0
weak_foot,18278.0,NaN,NaN,NaN,2.94425,0.664656,1.0,3.0,3.0,3.0,5.0
skill_moves,18278.0,NaN,NaN,NaN,2.368038,0.765038,1.0,2.0,2.0,3.0,5.0
work_rate,18278,9,Medium/Medium,9875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
body_type,18278,10,Normal,10750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
real_face,18278,2,No,16310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
release_clause_eur,16980.0,NaN,NaN,NaN,4740717.432273,11030016.291502,13000.0,563000.0,1200000.0,3700000.0,195800000.0
player_tags,1499,83,#Strength,514,NaN,NaN,NaN,NaN,NaN,NaN,NaN
team_position,18038,29,SUB,7820,NaN,NaN,NaN,NaN,NaN,NaN,NaN
team_jersey_number,18038.0,NaN,NaN,NaN,20.103892,16.603639,1.0,9.0,17.0,27.0,99.0
loaned_from,1048,316,Atalanta,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
joined,16990,1760,2019-07-01,1465,NaN,NaN,NaN,NaN,NaN,NaN,NaN
contract_valid_until,18038.0,NaN,NaN,NaN,2021.114591,1.289888,2019.0,2020.0,2021.0,2022.0,2026.0
nation_position,1126,26,SUB,587,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nation_jersey_number,1126.0,NaN,NaN,NaN,12.114565,6.735922,1.0,6.0,12.0,18.0,30.0
pace,16242.0,NaN,NaN,NaN,67.700899,11.297656,24.0,61.0,69.0,75.0,96.0
shooting,16242.0,NaN,NaN,NaN,52.298301,14.029418,15.0,42.0,54.0,63.0,93.0
passing,16242.0,NaN,NaN,NaN,57.233777,10.407844,24.0,50.0,58.0,64.0,92.0
dribbling,16242.0,NaN,NaN,NaN,62.531585,10.28495,23.0,57.0,64.0,69.0,96.0
defending,16242.0,NaN,NaN,NaN,51.553503,16.419528,15.0,36.0,56.0,65.0,90.0
physic,16242.0,NaN,NaN,NaN,64.876678,9.760162,27.0,59.0,66.0,72.0,90.0
gk_diving,2036.0,NaN,NaN,NaN,65.422397,7.736278,44.0,60.0,65.0,70.0,90.0
gk_handling,2036.0,NaN,NaN,NaN,63.146365,7.244023,42.0,58.0,63.0,68.0,92.0
gk_kicking,2036.0,NaN,NaN,NaN,61.832515,7.510709,35.0,57.0,61.0,66.0,93.0
gk_reflexes,2036.0,NaN,NaN,NaN,66.390472,8.154062,45.0,60.75,66.0,72.0,92.0
gk_speed,2036.0,NaN,NaN,NaN,37.798625,10.634038,12.0,29.0,39.0,46.0,65.0
gk_positioning,2036.0,NaN,NaN,NaN,63.374754,8.447876,41.0,58.0,64.0,69.0,91.0
player_traits,7566,921,Early Crosser,501,NaN,NaN,NaN,NaN,NaN,NaN,NaN
attacking_crossing,18278.0,NaN,NaN,NaN,49.718405,18.325403,5.0,38.0,54.0,64.0,93.0
attacking_finishing,18278.0,NaN,NaN,NaN,45.590218,19.594609,2.0,30.0,49.0,62.0,95.0
attacking_heading_accuracy,18278.0,NaN,NaN,NaN,52.221468,17.428429,5.0,44.0,56.0,64.0,93.0
attacking_short_passing,18278.0,NaN,NaN,NaN,58.748003,14.679653,7.0,54.0,62.0,68.0,92.0
attacking_volleys,18278.0,NaN,NaN,NaN,42.809388,17.701815,3.0,30.0,44.0,56.0,90.0
skill_dribbling,18278.0,NaN,NaN,NaN,55.596509,18.929118,4.0,50.0,61.0,68.0,97.0
skill_curve,18278.0,NaN,NaN,NaN,47.325692,18.422991,6.0,34.0,49.0,62.0,94.0
skill_fk_accuracy,18278.0,NaN,NaN,NaN,42.708885,17.433612,4.0,31.0,41.0,56.0,94.0
skill_long_passing,18278.0,NaN,NaN,NaN,52.768848,15.246454,8.0,43.0,56.0,64.0,92.0
skill_ball_control,18278.0,NaN,NaN,NaN,58.461976,16.741878,5.0,54.0,63.0,69.0,96.0
movement_acceleration,18278.0,NaN,NaN,NaN,64.299923,15.042232,12.0,56.0,67.0,75.0,97.0
movement_sprint_speed,18278.0,NaN,NaN,NaN,64.415746,14.847763,11.0,57.0,67.0,75.0,96.0
movement_agility,18278.0,NaN,NaN,NaN,63.504924,14.80838,11.0,55.0,66.0,74.0,96.0
movement_reactions,18278.0,NaN,NaN,NaN,61.752544,9.135613,21.0,56.0,62.0,68.0,96.0
movement_balance,18278.0,NaN,NaN,NaN,63.856439,14.201559,12.0,56.0,66.0,74.0,97.0
power_shot_power,18278.0,NaN,NaN,NaN,58.181694,13.326083,14.0,48.0,59.0,68.0,95.0
power_jumping,18278.0,NaN,NaN,NaN,64.928165,11.934059,19.0,58.0,66.0,73.0,95.0
power_stamina,18278.0,NaN,NaN,NaN,62.889485,16.017954,12.0,56.0,66.0,74.0,97.0
power_strength,18278.0,NaN,NaN,NaN,65.234763,12.534811,20.0,58.0,66.0,74.0,97.0
power_long_shots,18278.0,NaN,NaN,NaN,46.812945,19.322343,4.0,32.0,51.0,62.0,94.0
mentality_aggression,18278.0,NaN,NaN,NaN,55.742149,17.318157,9.0,44.0,58.0,69.0,95.0
mentality_interceptions,18278.0,NaN,NaN,NaN,46.380239,20.775812,3.0,25.0,52.0,64.0,92.0
mentality_positioning,18278.0,NaN,NaN,NaN,50.072163,19.594022,2.0,39.0,55.0,64.0,95.0
mentality_vision,18278.0,NaN,NaN,NaN,53.609749,13.955626,9.0,44.0,55.0,64.0,94.0
mentality_penalties,18278.0,NaN,NaN,NaN,48.383357,15.708099,7.0,39.0,49.0,60.0,92.0
mentality_composure,18278.0,NaN,NaN,NaN,58.528778,11.88084,12.0,51.0,60.0,67.0,96.0
defending_marking,18278.0,NaN,NaN,NaN,46.848889,20.091287,1.0,29.0,52.0,64.0,94.0
defending_standing_tackle,18278.0,NaN,NaN,NaN,47.640333,21.585641,5.0,27.0,55.0,66.0,92.0
defending_sliding_tackle,18278.0,NaN,NaN,NaN,45.606631,21.217734,3.0,24.0,52.0,64.0,90.0
goalkeeping_diving,18278.0,NaN,NaN,NaN,16.572765,17.738069,1.0,8.0,11.0,14.0,90.0
goalkeeping_handling,18278.0,NaN,NaN,NaN,16.354853,16.996925,1.0,8.0,11.0,14.0,92.0
goalkeeping_kicking,18278.0,NaN,NaN,NaN,16.212934,16.613665,1.0,8.0,11.0,14.0,93.0
goalkeeping_positioning,18278.0,NaN,NaN,NaN,16.368038,17.136497,1.0,8.0,11.0,14.0,91.0
goalkeeping_reflexes,18278.0,NaN,NaN,NaN,16.709924,18.038125,1.0,8.0,11.0,14.0,92.0
ls,16242,94,61+2,725,NaN,NaN,NaN,NaN,NaN,NaN,NaN
st,16242,94,61+2,725,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rs,16242,94,61+2,725,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lw,16242,107,63+2,736,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lf,16242,103,63+2,727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cf,16242,103,63+2,727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rf,16242,103,63+2,727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rw,16242,107,63+2,736,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lam,16242,103,61+2,748,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cam,16242,103,61+2,748,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ram,16242,103,61+2,748,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lm,16242,100,61+2,809,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lcm,16242,88,58+2,775,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cm,16242,88,58+2,775,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rcm,16242,88,58+2,775,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rm,16242,100,61+2,809,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lwb,16242,98,59+2,682,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ldm,16242,98,59+2,636,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cdm,16242,98,59+2,636,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rdm,16242,98,59+2,636,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rwb,16242,98,59+2,682,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lb,16242,96,61+2,667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lcb,16242,110,63+2,621,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cb,16242,110,63+2,621,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rcb,16242,110,63+2,621,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rb,16242,96,61+2,667,NaN,NaN,NaN,NaN,NaN,NaN,NaN

🔹 Missing values count:
loaned_from                   17230
nation_position               17152
nation_jersey_number          17152
player_tags                   16779
gk_kicking                    16242
gk_diving                     16242
gk_handling                   16242
gk_reflexes                   16242
gk_speed                      16242
gk_positioning                16242
player_traits                 10712
defending                      2036
pace                           2036
passing                        2036
dribbling                      2036
rs                             2036
lam                            2036
cam                            2036
rw                             2036
rf                             2036
physic                         2036
lf                             2036
lw                             2036
ram                            2036
cdm                            2036
rdm                            2036
rwb                            2036
lb                             2036
lcb                            2036
cb                             2036
lwb                            2036
ldm                            2036
rcb                            2036
rb                             2036
rm                             2036
rcm                            2036
cm                             2036
lcm                            2036
lm                             2036
shooting                       2036
st                             2036
ls                             2036
cf                             2036
release_clause_eur             1298
joined                         1288
contract_valid_until            240
team_position                   240
team_jersey_number              240
preferred_foot                    0
player_positions                  0
nationality                       0
club                              0
value_eur                         0
wage_eur                          0
height_cm                         0
weight_kg                         0
sofifa_id                         0
player_url                        0
short_name                        0
long_name                         0
age                               0
dob                               0
overall                           0
potential                         0
work_rate                         0
skill_moves                       0
international_reputation          0
weak_foot                         0
real_face                         0
body_type                         0
attacking_crossing                0
attacking_finishing               0
defending_standing_tackle         0
defending_marking                 0
mentality_composure               0
mentality_penalties               0
mentality_vision                  0
mentality_positioning             0
mentality_interceptions           0
mentality_aggression              0
power_long_shots                  0
power_strength                    0
power_stamina                     0
power_jumping                     0
power_shot_power                  0
movement_balance                  0
movement_reactions                0
movement_agility                  0
movement_sprint_speed             0
movement_acceleration             0
skill_ball_control                0
skill_long_passing                0
skill_fk_accuracy                 0
skill_curve                       0
skill_dribbling                   0
attacking_volleys                 0
attacking_short_passing           0
attacking_heading_accuracy        0
goalkeeping_kicking               0
goalkeeping_handling              0
goalkeeping_reflexes              0
goalkeeping_positioning           0
defending_sliding_tackle          0
goalkeeping_diving                0
dtype: int64

🔹 Number of duplicate rows:
0

🔹 First 5 rows of the dataset:

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [ ]:
df.shape

(18278, 104)

#  1. Data Wrangling & Preprocessing

In [ ]:
import pandas as pd
import numpy as np

# Create a copy of the original dataset
df_cleaned = df.copy()

# Step 1: Positional columns to transform
positional_cols = ['ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw',
                   'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm',
                   'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb',
                   'rcb', 'rb']

# Step 1.1: Function to extract bonus % score
def extract_base_bonus(val):
    if isinstance(val, str) and '+' in val:
        base, bonus = val.split('+')
        return float(base), float(bonus)
    try:
        return float(val), 0.0
    except:
        return np.nan, 0.0

def compute_bonus_percent(base, bonus):
    if pd.isna(base) or base == 0:
        return np.nan
    return round((bonus / base) * 100, 2)

# Step 1.2: Create new score columns and drop original ones
for col in positional_cols:
    if col in df_cleaned.columns:
        extracted = df_cleaned[col].apply(extract_base_bonus)
        df_cleaned[f'{col}_score'] = [compute_bonus_percent(base, bonus) for base, bonus in extracted]
        df_cleaned.drop(columns=[col], inplace=True)

# Step 2: Drop irrelevant or unneeded columns
columns_to_drop = ['sofifa_id', 'player_url', 'long_name', 'dob']
df_cleaned.drop(columns=columns_to_drop, inplace=True)

# Step 3: Identify columns with more than 90% missing values
high_missing_cols = df_cleaned.columns[df_cleaned.isnull().mean() > 0.90].tolist()

# ✅ Output
print("✅ Positional performance bonus columns created. Sample output:")
display(df_cleaned[[col + '_score' for col in positional_cols]].head())

print(f"⚠️ Columns with more than 90% missing values:\n{high_missing_cols}")

✅ Positional performance bonus columns created. Sample output:

,ls_score,st_score,rs_score,lw_score,lf_score,cf_score,rf_score,rw_score,lam_score,cam_score,...,lwb_score,ldm_score,cdm_score,rdm_score,rwb_score,lb_score,lcb_score,cb_score,rcb_score,rb_score
0,2.25,2.25,2.25,2.15,2.15,2.15,2.15,2.15,2.15,2.15,...,2.94,3.03,3.03,3.03,2.94,3.17,3.85,3.85,3.85,3.17
1,3.30,3.30,3.30,3.37,3.33,3.33,3.33,3.37,3.41,3.41,...,4.62,4.92,4.92,4.92,4.62,4.92,5.66,5.66,5.66,4.92
2,3.57,3.57,3.57,3.33,3.37,3.37,3.37,3.33,3.33,3.33,...,4.55,4.92,4.92,4.92,4.55,4.92,6.52,6.52,6.52,4.92
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.61,3.61,3.61,3.37,3.41,3.41,3.41,3.37,3.37,3.37,...,4.55,4.76,4.76,4.76,4.55,4.92,6.12,6.12,6.12,4.92

⚠️ Columns with more than 90% missing values:
['player_tags', 'loaned_from', 'nation_position', 'nation_jersey_number']

In [ ]:
df_cleaned.head()
df_cleaned.shape

(18278, 100)

In [ ]:
df_cleaned.columns.to_list()

['short_name',
 'age',
 'height_cm',
 'weight_kg',
 'nationality',
 'club',
 'overall',
 'potential',
 'value_eur',
 'wage_eur',
 'player_positions',
 'preferred_foot',
 'international_reputation',
 'weak_foot',
 'skill_moves',
 'work_rate',
 'body_type',
 'real_face',
 'release_clause_eur',
 'player_tags',
 'team_position',
 'team_jersey_number',
 'loaned_from',
 'joined',
 'contract_valid_until',
 'nation_position',
 'nation_jersey_number',
 'pace',
 'shooting',
 'passing',
 'dribbling',
 'defending',
 'physic',
 'gk_diving',
 'gk_handling',
 'gk_kicking',
 'gk_reflexes',
 'gk_speed',
 'gk_positioning',
 'player_traits',
 'attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control',
 'movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance',
 'power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots',
 'mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure',
 'defending_marking',
 'defending_standing_tackle',
 'defending_sliding_tackle',
 'goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'ls_score',
 'st_score',
 'rs_score',
 'lw_score',
 'lf_score',
 'cf_score',
 'rf_score',
 'rw_score',
 'lam_score',
 'cam_score',
 'ram_score',
 'lm_score',
 'lcm_score',
 'cm_score',
 'rcm_score',
 'rm_score',
 'lwb_score',
 'ldm_score',
 'cdm_score',
 'rdm_score',
 'rwb_score',
 'lb_score',
 'lcb_score',
 'cb_score',
 'rcb_score',
 'rb_score']

## Unforgivable amount of the null values
loaned_from            94.27%
nation_position        93.85%
nation_jersey_number   93.85%
player_tags            91.84%
gk_kicking             88.83%
gk_diving              88.83%
gk_handling            88.83%
gk_reflexes            88.83%
gk_speed               88.83%
gk_positioning         88.83%

In [ ]:


# Step 1.1 (continued): Drop sparse & non-critical columns
columns_to_drop = [
    'loaned_from',               # Sparse and often irrelevant for analysis
    'nation_position',           # Sparse and redundant with club position
    'nation_jersey_number',      # Sparse, not useful for performance
    'player_tags'                # Mostly unstructured, high missing
]

# Drop selected columns
df_cleaned.drop(columns=columns_to_drop, inplace=True)

# ✅ Explanation: Why we are keeping GK-specific columns
# We are retaining the following goalkeeper-specific attributes:
# - 'gk_kicking', 'gk_diving', 'gk_handling', 'gk_reflexes', 'gk_speed', 'gk_positioning'
# Even though they have high missingness overall, they are crucial for analyzing goalkeepers.
# Goalkeepers are fewer in number, and these columns are applicable only to them.

print(f"Dropped {len(columns_to_drop)} columns with high missing values and low analytical relevance.")
print("✅ Retained GK-related columns for goalkeeper-specific analysis.")

Dropped 4 columns with high missing values and low analytical relevance.
✅ Retained GK-related columns for goalkeeper-specific analysis.

In [ ]:
df_cleaned.shape

(18278, 96)

In [ ]:
df_cleaned.head()
# df_cleaned.shape

,short_name,age,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,...,lwb_score,ldm_score,cdm_score,rdm_score,rwb_score,lb_score,lcb_score,cb_score,rcb_score,rb_score
0,L. Messi,32,170,72,Argentina,FC Barcelona,94,94,95500000,565000,...,2.94,3.03,3.03,3.03,2.94,3.17,3.85,3.85,3.85,3.17
1,Cristiano Ronaldo,34,187,83,Portugal,Juventus,93,93,58500000,405000,...,4.62,4.92,4.92,4.92,4.62,4.92,5.66,5.66,5.66,4.92
2,Neymar Jr,27,175,68,Brazil,Paris Saint-Germain,92,92,105500000,290000,...,4.55,4.92,4.92,4.92,4.55,4.92,6.52,6.52,6.52,4.92
3,J. Oblak,26,188,87,Slovenia,Atlético Madrid,91,93,77500000,125000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E. Hazard,28,175,74,Belgium,Real Madrid,91,91,90000000,470000,...,4.55,4.76,4.76,4.76,4.55,4.92,6.12,6.12,6.12,4.92

In [ ]:
df.columns.to_list()

['sofifa_id',
 'player_url',
 'short_name',
 'long_name',
 'age',
 'dob',
 'height_cm',
 'weight_kg',
 'nationality',
 'club',
 'overall',
 'potential',
 'value_eur',
 'wage_eur',
 'player_positions',
 'preferred_foot',
 'international_reputation',
 'weak_foot',
 'skill_moves',
 'work_rate',
 'body_type',
 'real_face',
 'release_clause_eur',
 'player_tags',
 'team_position',
 'team_jersey_number',
 'loaned_from',
 'joined',
 'contract_valid_until',
 'nation_position',
 'nation_jersey_number',
 'pace',
 'shooting',
 'passing',
 'dribbling',
 'defending',
 'physic',
 'gk_diving',
 'gk_handling',
 'gk_kicking',
 'gk_reflexes',
 'gk_speed',
 'gk_positioning',
 'player_traits',
 'attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control',
 'movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance',
 'power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots',
 'mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure',
 'defending_marking',
 'defending_standing_tackle',
 'defending_sliding_tackle',
 'goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'ls',
 'st',
 'rs',
 'lw',
 'lf',
 'cf',
 'rf',
 'rw',
 'lam',
 'cam',
 'ram',
 'lm',
 'lcm',
 'cm',
 'rcm',
 'rm',
 'lwb',
 'ldm',
 'cdm',
 'rdm',
 'rwb',
 'lb',
 'lcb',
 'cb',
 'rcb',
 'rb']

## Add best_position Column:

In [ ]:
# Step 1: Positional columns used earlier
positional_cols = ['ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw',
                   'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm',
                   'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb',
                   'rcb', 'rb']

# Step 2: Create the list of score columns
score_cols = [f"{col}_score" for col in positional_cols]

# Step 3: Find the position with the highest score for each player
df_cleaned['best_position'] = df_cleaned[score_cols].idxmax(axis=1).str.replace('_score', '')

# (Optional) Add best_position_score column for reference
df_cleaned['best_position_score'] = df_cleaned[score_cols].max(axis=1)

# Step 4: Display some results
print("✅ 'best_position' and 'best_position_score' columns added.")
display(df_cleaned[['short_name', 'best_position', 'best_position_score'] + score_cols].head(10))

✅ 'best_position' and 'best_position_score' columns added.

/tmp/ipython-input-215-2064082824.py:11: FutureWarning: The behavior of DataFrame.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  df_cleaned['best_position'] = df_cleaned[score_cols].idxmax(axis=1).str.replace('_score', '')

,short_name,best_position,best_position_score,ls_score,st_score,rs_score,lw_score,lf_score,cf_score,rf_score,...,lwb_score,ldm_score,cdm_score,rdm_score,rwb_score,lb_score,lcb_score,cb_score,rcb_score,rb_score
0,L. Messi,lcb,3.85,2.25,2.25,2.25,2.15,2.15,2.15,2.15,...,2.94,3.03,3.03,3.03,2.94,3.17,3.85,3.85,3.85,3.17
1,Cristiano Ronaldo,lcb,5.66,3.30,3.30,3.30,3.37,3.33,3.33,3.33,...,4.62,4.92,4.92,4.92,4.62,4.92,5.66,5.66,5.66,4.92
2,Neymar Jr,lcb,6.52,3.57,3.57,3.57,3.33,3.37,3.37,3.37,...,4.55,4.92,4.92,4.92,4.55,4.92,6.52,6.52,6.52,4.92
3,J. Oblak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E. Hazard,lcb,6.12,3.61,3.61,3.61,3.37,3.41,3.41,3.41,...,4.55,4.76,4.76,4.76,4.55,4.92,6.12,6.12,6.12,4.92
5,K. De Bruyne,lcb,4.55,3.66,3.66,3.66,3.45,3.45,3.45,3.45,...,3.90,3.90,3.90,3.90,3.90,4.11,4.55,4.55,4.55,4.11
6,M. ter Stegen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,V. van Dijk,lw,4.48,4.35,4.35,4.35,4.48,4.35,4.35,4.35,...,3.80,3.61,3.61,3.61,3.80,3.70,3.45,3.45,3.45,3.70
8,L. Modrić,lcb,4.17,3.90,3.90,3.90,3.57,3.61,3.61,3.61,...,3.70,3.70,3.70,3.70,3.70,3.80,4.17,4.17,4.17,3.80
9,M. Salah,lcb,5.26,3.57,3.57,3.57,3.41,3.41,3.41,3.41,...,4.29,4.48,4.48,4.48,4.29,4.55,5.26,5.26,5.26,4.55

In [ ]:
df_cleaned.columns.to_list()

['short_name',
 'age',
 'height_cm',
 'weight_kg',
 'nationality',
 'club',
 'overall',
 'potential',
 'value_eur',
 'wage_eur',
 'player_positions',
 'preferred_foot',
 'international_reputation',
 'weak_foot',
 'skill_moves',
 'work_rate',
 'body_type',
 'real_face',
 'release_clause_eur',
 'team_position',
 'team_jersey_number',
 'joined',
 'contract_valid_until',
 'pace',
 'shooting',
 'passing',
 'dribbling',
 'defending',
 'physic',
 'gk_diving',
 'gk_handling',
 'gk_kicking',
 'gk_reflexes',
 'gk_speed',
 'gk_positioning',
 'player_traits',
 'attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control',
 'movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance',
 'power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots',
 'mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure',
 'defending_marking',
 'defending_standing_tackle',
 'defending_sliding_tackle',
 'goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'ls_score',
 'st_score',
 'rs_score',
 'lw_score',
 'lf_score',
 'cf_score',
 'rf_score',
 'rw_score',
 'lam_score',
 'cam_score',
 'ram_score',
 'lm_score',
 'lcm_score',
 'cm_score',
 'rcm_score',
 'rm_score',
 'lwb_score',
 'ldm_score',
 'cdm_score',
 'rdm_score',
 'rwb_score',
 'lb_score',
 'lcb_score',
 'cb_score',
 'rcb_score',
 'rb_score',
 'best_position',
 'best_position_score']

In [ ]:
df_cleaned.shape

(18278, 98)

In [ ]:
print(df.isnull().sum().sort_values(ascending=False))

loaned_from                   17230
nation_position               17152
nation_jersey_number          17152
player_tags                   16779
gk_kicking                    16242
gk_diving                     16242
gk_handling                   16242
gk_reflexes                   16242
gk_speed                      16242
gk_positioning                16242
player_traits                 10712
defending                      2036
pace                           2036
passing                        2036
dribbling                      2036
rs                             2036
lam                            2036
cam                            2036
rw                             2036
rf                             2036
physic                         2036
lf                             2036
lw                             2036
ram                            2036
cdm                            2036
rdm                            2036
rwb                            2036
lb                             2036
lcb                            2036
cb                             2036
lwb                            2036
ldm                            2036
rcb                            2036
rb                             2036
rm                             2036
rcm                            2036
cm                             2036
lcm                            2036
lm                             2036
shooting                       2036
st                             2036
ls                             2036
cf                             2036
release_clause_eur             1298
joined                         1288
contract_valid_until            240
team_position                   240
team_jersey_number              240
preferred_foot                    0
player_positions                  0
nationality                       0
club                              0
value_eur                         0
wage_eur                          0
height_cm                         0
weight_kg                         0
sofifa_id                         0
player_url                        0
short_name                        0
long_name                         0
age                               0
dob                               0
overall                           0
potential                         0
work_rate                         0
skill_moves                       0
international_reputation          0
weak_foot                         0
real_face                         0
body_type                         0
attacking_crossing                0
attacking_finishing               0
defending_standing_tackle         0
defending_marking                 0
mentality_composure               0
mentality_penalties               0
mentality_vision                  0
mentality_positioning             0
mentality_interceptions           0
mentality_aggression              0
power_long_shots                  0
power_strength                    0
power_stamina                     0
power_jumping                     0
power_shot_power                  0
movement_balance                  0
movement_reactions                0
movement_agility                  0
movement_sprint_speed             0
movement_acceleration             0
skill_ball_control                0
skill_long_passing                0
skill_fk_accuracy                 0
skill_curve                       0
skill_dribbling                   0
attacking_volleys                 0
attacking_short_passing           0
attacking_heading_accuracy        0
goalkeeping_kicking               0
goalkeeping_handling              0
goalkeeping_reflexes              0
goalkeeping_positioning           0
defending_sliding_tackle          0
goalkeeping_diving                0
dtype: int64

In [ ]:
print(df_cleaned.isnull().sum().sort_values(ascending=False))

gk_reflexes                   16242
gk_speed                      16242
gk_handling                   16242
gk_diving                     16242
gk_kicking                    16242
gk_positioning                16242
player_traits                 10712
passing                        2036
physic                         2036
defending                      2036
dribbling                      2036
cam_score                      2036
ram_score                      2036
lm_score                       2036
rw_score                       2036
rf_score                       2036
shooting                       2036
pace                           2036
rwb_score                      2036
lb_score                       2036
lcb_score                      2036
cb_score                       2036
lwb_score                      2036
ldm_score                      2036
cdm_score                      2036
rdm_score                      2036
rcb_score                      2036
rb_score                       2036
best_position                  2036
best_position_score            2036
rm_score                       2036
rcm_score                      2036
cm_score                       2036
lcm_score                      2036
lf_score                       2036
cf_score                       2036
rs_score                       2036
lw_score                       2036
ls_score                       2036
st_score                       2036
lam_score                      2036
release_clause_eur             1298
joined                         1288
team_jersey_number              240
team_position                   240
contract_valid_until            240
height_cm                         0
weight_kg                         0
body_type                         0
real_face                         0
short_name                        0
age                               0
nationality                       0
club                              0
overall                           0
potential                         0
value_eur                         0
wage_eur                          0
player_positions                  0
preferred_foot                    0
international_reputation          0
weak_foot                         0
skill_moves                       0
work_rate                         0
attacking_crossing                0
attacking_finishing               0
goalkeeping_diving                0
defending_sliding_tackle          0
defending_standing_tackle         0
defending_marking                 0
mentality_composure               0
mentality_penalties               0
mentality_vision                  0
mentality_positioning             0
mentality_interceptions           0
mentality_aggression              0
power_long_shots                  0
power_strength                    0
power_stamina                     0
power_jumping                     0
power_shot_power                  0
movement_balance                  0
movement_reactions                0
movement_agility                  0
movement_sprint_speed             0
movement_acceleration             0
skill_ball_control                0
skill_long_passing                0
skill_fk_accuracy                 0
skill_curve                       0
skill_dribbling                   0
attacking_volleys                 0
attacking_short_passing           0
attacking_heading_accuracy        0
goalkeeping_reflexes              0
goalkeeping_positioning           0
goalkeeping_kicking               0
goalkeeping_handling              0
dtype: int64

In [ ]:
df_cleaned.shape

(18278, 98)

In [ ]:
# # Save the cleaned DataFrame to a CSV file
# df_cleaned.to_csv("fifa20_cleaned_final11.csv", index=False)

# # Download it (works in Colab)
# from google.colab import files
# files.download("fifa20_cleaned_final11.csv")

In [ ]:
# Count how many players have 'GK' listed in their player_positions
df_cleaned['player_positions'].str.contains("GK").sum()

np.int64(2036)

# ✅ Drop Rows with >30% Missing in Selected Columns Only

In [ ]:
import numpy as np

# List of target columns to impute
target_cols = [
    'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic',
    'ls_score', 'st_score', 'rs_score', 'lw_score', 'lf_score', 'cf_score', 'rf_score', 'rw_score',
    'lam_score', 'cam_score', 'ram_score', 'lm_score', 'lcm_score', 'cm_score', 'rcm_score', 'rm_score',
    'lwb_score', 'ldm_score', 'cdm_score', 'rdm_score', 'rwb_score', 'lb_score', 'lcb_score', 'cb_score',
    'rcb_score', 'rb_score', 'best_position', 'best_position_score'
]

# Separate numerical and categorical
numerical_cols = [col for col in target_cols if df_cleaned[col].dtype != 'object']
categorical_cols = [col for col in target_cols if df_cleaned[col].dtype == 'object']

# Impute numerical columns with median
for col in numerical_cols:
    median_val = df_cleaned[col].median()
    df_cleaned[col] = df_cleaned[col].fillna(median_val)

# Impute categorical columns with mode
for col in categorical_cols:
    mode_val = df_cleaned[col].mode()[0]
    df_cleaned[col] = df_cleaned[col].fillna(mode_val)

# ✅ Output summary
print("✅ Imputed missing values:")
print(f"   🔢 Numerical columns: {len(numerical_cols)} → median used")
print(f"   🔤 Categorical columns: {len(categorical_cols)} → mode used")
print(f"📊 Final dataset shape: {df_cleaned.shape}")

✅ Imputed missing values:
   🔢 Numerical columns: 33 → median used
   🔤 Categorical columns: 1 → mode used
📊 Final dataset shape: (18278, 98)

## check

In [ ]:
# Count how many players have 'GK' listed in their player_positions
df_cleaned['player_positions'].str.contains("GK").sum()

np.int64(2036)

# 🧩 1.2 Impute Missing Values – Strategy

## Parsing befor Imputing

In [ ]:
# df_cleaned['value_eur'].unique()
string_values = df_cleaned[df_cleaned['value_eur'].apply(lambda x: isinstance(x, str))]
print(string_values)

Empty DataFrame
Columns: [short_name, age, height_cm, weight_kg, nationality, club, overall, potential, value_eur, wage_eur, player_positions, preferred_foot, international_reputation, weak_foot, skill_moves, work_rate, body_type, real_face, release_clause_eur, team_position, team_jersey_number, joined, contract_valid_until, pace, shooting, passing, dribbling, defending, physic, gk_diving, gk_handling, gk_kicking, gk_reflexes, gk_speed, gk_positioning, player_traits, attacking_crossing, attacking_finishing, attacking_heading_accuracy, attacking_short_passing, attacking_volleys, skill_dribbling, skill_curve, skill_fk_accuracy, skill_long_passing, skill_ball_control, movement_acceleration, movement_sprint_speed, movement_agility, movement_reactions, movement_balance, power_shot_power, power_jumping, power_stamina, power_strength, power_long_shots, mentality_aggression, mentality_interceptions, mentality_positioning, mentality_vision, mentality_penalties, mentality_composure, defending_marking, defending_standing_tackle, defending_sliding_tackle, goalkeeping_diving, goalkeeping_handling, goalkeeping_kicking, goalkeeping_positioning, goalkeeping_reflexes, ls_score, st_score, rs_score, lw_score, lf_score, cf_score, rf_score, rw_score, lam_score, cam_score, ram_score, lm_score, lcm_score, cm_score, rcm_score, rm_score, lwb_score, ldm_score, cdm_score, rdm_score, rwb_score, lb_score, lcb_score, cb_score, rcb_score, rb_score, best_position, best_position_score]
Index: []

[0 rows x 98 columns]

## ✅ Code: Parse + Impute value_eur and wage_eur in df_cleaned

In [ ]:
def parse_currency(val):
    if pd.isnull(val): return np.nan
    if isinstance(val, (int, float)): return val
    val = str(val).replace('€', '').strip().upper()
    if 'M' in val:
        return float(val.replace('M', '')) * 1_000_000
    elif 'K' in val:
        return float(val.replace('K', '')) * 1_000
    try:
        return float(val)
    except:
        return np.nan

for col in ['value_eur', 'wage_eur']:
    df_cleaned[col] = df_cleaned[col].apply(parse_currency)

    # Replace 0 values with the median of non-zero values
    median_val = df_cleaned.loc[df_cleaned[col] != 0, col].median()
    df_cleaned[col] = df_cleaned[col].replace(0, median_val)

    print(f"✅ '{col}' parsed and 0s replaced.")
    print(f"   {col} median used: €{int(median_val):,}")

✅ 'value_eur' parsed and 0s replaced.
   value_eur median used: €725,000
✅ 'wage_eur' parsed and 0s replaced.
   wage_eur median used: €3,000

In [ ]:
print(df_cleaned["value_eur"].info())
df_cleaned["wage_eur"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 18278 entries, 0 to 18277
Series name: value_eur
Non-Null Count  Dtype
--------------  -----
18278 non-null  int64
dtypes: int64(1)
memory usage: 142.9 KB
None
<class 'pandas.core.series.Series'>
RangeIndex: 18278 entries, 0 to 18277
Series name: wage_eur
Non-Null Count  Dtype
--------------  -----
18278 non-null  int64
dtypes: int64(1)
memory usage: 142.9 KB

In [ ]:
# Count how many players have 'GK' listed in their player_positions
df_cleaned['player_positions'].str.contains("GK").sum()

np.int64(2036)

# 🛠 Options for Removing Duplicates
Let’s assume "short_name" or "long_name" represents the player name. But we should be smart about which duplicate to keep.

# ✅ Best Strategy:
Keep the most recent or best version of each player — e.g., with:

Highest overall rating, or

Highest value_eur

## 🔍 Code to Remove Duplicates (Keep Best Version)

In [ ]:
# Count how many players have 'GK' listed in their player_positions
df_cleaned['player_positions'].str.contains("GK").sum()

np.int64(2036)

In [ ]:
# Step 1: Sort by 'overall' so best version appears first
df_cleaned_sorted = df_cleaned.sort_values(by='overall', ascending=False)

# Step 2: Identify duplicate player entries (all except first occurrence)
duplicates_dropped = df_cleaned_sorted[df_cleaned_sorted.duplicated(subset='short_name', keep='first')]

# Step 3: Drop duplicates, keeping the best one
df_cleaned = df_cleaned_sorted.drop_duplicates(subset='short_name', keep='first').reset_index(drop=True)

# Output
print(f"✅ Removed {len(duplicates_dropped)} duplicate player records.")
print(f"📊 New shape of df_cleaned: {df_cleaned.shape}")

# Optional: Display the names of dropped players
print("🗃️ List of dropped duplicate players:")
display(duplicates_dropped[['short_name', 'overall', 'club', 'age', 'value_eur']])

✅ Removed 924 duplicate player records.
📊 New shape of df_cleaned: (17354, 98)
🗃️ List of dropped duplicate players:

,short_name,overall,club,age,value_eur
430,M. Dembélé,80,Olympique Lyonnais,22,20000000
693,Mariano,79,Galatasaray SK,33,5500000
832,Fernando,78,Beijing Sinobo Guoan FC,27,11000000
898,Marcelo,78,Olympique Lyonnais,32,6500000
958,Naldo,78,RCD Espanyol,30,8500000
780,N. Maksimović,78,Getafe CF,24,14000000
1010,L. Martínez,77,Ajax,21,12000000
1102,Paulinho,77,SC Braga,26,11000000
1116,Bruno,77,Getafe CF,29,8500000
1151,Danilo,77,Bologna,35,2700000
1237,L. López,77,Boca Juniors,29,7500000
1209,R. Funes Mori,77,Monterrey,28,9000000
1004,A. Miranchuk,77,Lokomotiv Moscow,23,13000000
1365,Fernandinho,76,Hebei China Fortune FC,26,9500000
1345,Paulinho,76,Portimonense SC,24,10000000
1375,Otávio,76,FC Girondins de Bordeaux,25,8500000
1413,Guilherme,76,Olympiacos CFP,28,7500000
1439,M. Gómez,76,VfB Stuttgart,33,4800000
1513,L. Acosta,76,Club Atlético Lanús,31,7000000
1545,J. Martínez,76,Portimonense SC,32,6000000
1542,Adrián,76,Liverpool,32,4700000
1592,M. Díaz,76,Boca Juniors,33,4200000
1617,N. Domínguez,75,Vélez Sarsfield,21,12000000
1680,J. Hernández,75,Watford,20,9500000
1734,Danilo,75,OGC Nice,23,9000000
1752,Gabriel,75,Lecce,26,6500000
1811,J. Rodríguez,75,Cruz Azul,25,8500000
1818,Rodrigo,75,PAOK,26,7000000
1892,Rafael,75,Cagliari,37,675000
1901,J. Corona,75,Cruz Azul,38,675000
1975,J. Hernández,75,Pachuca,30,5500000
1967,I. Traoré,75,Angers SCO,32,4300000
2005,L. Rodríguez,75,Tigres U.A.N.L.,28,5500000
1993,Éder,75,Lokomotiv Moscow,31,6000000
2033,Caio,75,Al Ain FC,28,7000000
2044,Guilherme,75,Yeni Malatyaspor,28,6500000
2643,Douglas,74,Shimizu S-Pulse,31,5000000
2151,P. Diop,74,RC Celta,21,8500000
2178,Joaquín,74,Real Valladolid CF,23,7500000
2195,P. Cissé,74,Olympiacos CFP,23,7000000
2198,L. Rodríguez,74,DC United,22,8000000
2246,A. Touré,74,Eintracht Frankfurt,23,6500000
2266,R. Thomas,74,PSV,24,7000000
2276,J. Rodríguez,74,Guadalajara,26,5000000
2310,Charles,74,Clube Sport Marítimo,25,5000000
2338,Maurício,74,Urawa Red Diamonds,27,6000000
2372,Munir,74,Málaga CF,30,4400000
2380,Felipe,74,SPAL,34,2100000
2406,S. Larsson,74,AIK,34,2700000
2413,P. Aguilar,74,Club América,33,2500000
2495,Sandro,74,Genoa,30,4600000
2504,L. Sané,74,Orlando City SC,32,3600000
2508,Rafael,74,Reading,29,4000000
2514,J. Larsen,74,Udinese,28,4800000
2583,S. Romero,74,Independiente,30,5500000
2560,Pedro Henrique,74,Kayserispor,29,5500000
2647,I. Traoré,74,SK Slavia Praha,30,5000000
2748,B. Kamara,73,RC Strasbourg Alsace,22,4100000
2800,Marcão,73,Hebei China Fortune FC,25,5500000
2867,Iago,73,Moreirense FC,27,4300000
2979,G. Rodríguez,73,San Lorenzo de Almagro,35,1200000
2981,R. Martínez,73,Club Atlético Aldosivi,36,1300000
3015,M. Jensen,73,Rosenborg BK,31,3400000
3084,Wallace,73,Göztepe SK,31,3000000
3103,Oier,73,CA Osasuna,33,1900000
3116,Paulinho,73,BK Häcken,33,2400000
3134,Juan Carlos,73,Girona FC,31,2600000
3129,Douglas,73,Beşiktaş JK,28,3400000
3162,S. García,73,Deportivo Toluca,30,3200000
3176,Patric,73,Gamba Osaka,31,3600000
3224,A. Correa,73,Once Caldas,34,1500000
2703,Gabriel,73,LOSC Lille,21,5500000
3295,Jota,72,SL Benfica,20,6000000
3307,J. Lewis,72,Norwich City,21,4900000
3374,B. Davies,72,Preston North End,23,3900000
3405,M. Suárez,72,Montpellier HSC,23,3900000
3344,J. Murillo,72,CD Tondela,23,4800000
3421,M. Moreno,72,Portimonense SC,22,4300000
3378,Saúl,72,Deportivo Alavés,24,3900000
3408,A. González,72,Monterrey,24,4200000
3425,Aitor,72,FC Twente,23,4300000
3433,J. Rodríguez,72,Club León,23,3900000
3443,J. Jones,72,Rangers FC,24,4200000
3476,G. Fernández,72,RC Celta,25,4200000
3609,J. Correa,72,Club Atlas,26,3800000
3707,G. Fernández,72,Estudiantes de La Plata,35,1400000
3667,Danilo,72,VfL Bochum 1848,27,3100000
3819,Álvaro,72,Birmingham City,28,3200000
3839,Souza,72,Cerezo Osaka,31,2700000
3951,L. Castro,72,Kaizer Chiefs,30,3000000
3954,E. Insúa,72,Panathinaikos FC,28,2700000
4055,G. Pezzella,71,Udinese,21,3900000
4059,Emerson,71,Real Betis,20,3900000
4068,M. Wagué,71,FC Barcelona,20,3700000
4079,J. González,71,Monterrey,20,3800000
4085,Manu García,71,Real Sporting de Gijón,21,3700000
4102,L. Suárez,71,Villarreal CF,23,3500000
4106,Matheus Pereira,71,Juventus,21,3500000
4126,J. Rodríguez,71,Club Atlético Banfield,23,3000000
4137,Murilo,71,FC Paços de Ferreira,23,3300000
4164,J. Lucumi,71,Querétaro,24,3200000
4177,M. Pérez,71,Guadalajara,26,2800000
4221,J. Murphy,71,Sheffield Wednesday,24,3100000
4279,J. Rodríguez,71,Once Caldas,26,2900000
4280,M. Rodríguez,71,U.N.A.M.,24,3000000
4299,S. Davis,71,New York Red Bulls,26,2900000
4347,M. Mohammadi,71,CD Aves,25,2900000
4369,William,71,Al Faisaly,27,2800000
4393,L. Díaz,71,Atlético Tucumán,27,2800000
4399,J. Correa,71,Clube Sport Marítimo,26,2800000
4423,A. Turan,71,Atiker Konyaspor,35,725000
4429,S. Silva,71,Argentinos Juniors,38,850000
4487,William,71,Deportivo Toluca,32,1800000
4500,D. González,71,Independiente Medellín,36,400000
4507,B. Angulo,71,Puebla FC,29,2000000
4527,Felipe,71,Hannover 96,32,1500000
4530,A. Costa,71,Atlético Nacional,34,1200000
4533,J. Murphy,71,Rangers FC,29,2300000
4595,Rodri,71,Granada CF,29,2400000
4604,Joselu,71,Real Oviedo,28,2400000
4606,J. Sánchez,71,Guadalajara,29,2000000
4641,Marcelo,71,Chicago Fire,29,2000000
4676,B. Acosta,71,SK Brann,32,1500000
4044,Paulinho,71,Bayer 04 Leverkusen,18,4900000
4046,Fernando,71,Shakhtar Donetsk,20,5000000
4747,Luisinho,71,Al Faisaly,28,2400000
4802,C. Bravo,70,Club Atlético Banfield,22,2800000
4780,H. Abe,70,FC Barcelona,20,3400000
4822,M. Fofana,70,FC Metz,21,2700000
4965,Bernardo,70,Granada CF,25,2100000
5033,A. Davies,70,Stoke City,26,1700000
5038,Carlinhos,70,Vitória de Setúbal,25,2300000
5075,A. Diallo,70,Gençlerbirliği SK,27,1600000
5119,Bruno,70,Olympiacos CFP,25,2200000
5144,J. Andersen,70,Hammarby IF,26,2100000
5153,Lucas Fernandes,70,Hokkaido Consadole Sapporo,25,2200000
5158,J. Vuković,70,Clube Sport Marítimo,27,1900000
5165,A. Turan,70,Kayserispor,27,1800000
5204,D. Rodríguez,70,Central Córdoba,30,1400000
5218,C. Traoré,70,FC Nantes,27,1800000
5294,S. Hutchinson,70,Sheffield Wednesday,29,1500000
5365,M. Rodríguez,70,Universidad de Chile,33,800000
5339,A. Ríos,70,San Jose Earthquakes,29,1800000
5425,I. Sylla,70,KV Oostende,28,1800000
5441,R. Rojas,70,Paraguay,31,725000
5449,J. Corona,70,LA Galaxy,28,1800000
5467,Soares,70,Gil Vicente FC,30,1500000
5536,Paulinho,70,AEK Athens,27,1600000
5515,A. Henríquez,70,Atlético Nacional,36,350000
5517,Felipe,70,DC United,28,1800000
5550,J. Cuadrado,70,Atlético Nacional,34,775000
5561,R. Fernández,70,Al Fayha,28,1800000
5530,L. Jiménez,70,Tiburones Rojos de Veracruz,30,1400000
5571,L. Lollo,70,Club Atlético Banfield,32,1100000
5576,J. Domínguez,70,Alianza Petrolera,32,1200000
5577,Gabriel,70,Dinamo Bucureşti,31,1300000
5546,B. Sarr,70,Damac FC,28,1600000
5594,J. Sánchez,70,Junior FC,31,1300000
5650,D. Valdés,70,Deportes Tolima,28,1800000
5627,L. Castro,70,Independiente Medellín,27,1900000
4766,R. Vargas,70,FC Augsburg,20,3900000
6342,Charles,69,Antalyaspor,34,400000
6139,Matheus,69,Royal Antwerp FC,27,1100000
6107,Ewerton,69,Urawa Red Diamonds,26,1200000
6150,J. Agudelo,69,New England Revolution,26,1300000
6197,S. Dursun,69,Antalyaspor,27,1100000
6212,S. Johnson,69,Real Salt Lake,26,1300000
6224,B. Fernández,69,Patriotas Boyacá FC,27,1200000
6508,D. Sánchez,69,Unión Española,32,650000
6545,M. Benítez,69,Defensa y Justicia,28,1000000
6547,M. Çelik,69,Gazişehir Gaziantep F.K.,29,1000000
6514,A. Ramos,69,CD Everton de Viña del Mar,27,1100000
6517,N. Ibáñez,69,Newell's Old Boys,37,110000
6519,R. Salinas,69,Newell's Old Boys,32,850000
6593,L. Reyes,69,Atlético de San Luis,28,900000
6609,C. Burke,69,Philadelphia Union,27,1100000
6561,A. Aguilar,69,Paraguay,30,725000
6389,M. Rojas,69,SønderjyskE,27,1100000
6403,J. Collins,69,Luton Town,28,1100000
6489,J. Palomino,69,Envigado FC,30,875000
5870,A. Pérez,69,Querétaro,25,1300000
5863,Varela,69,Os Belenenses,24,1300000
5697,M. Smith,69,Queens Park Rangers,19,1800000
5675,L. Pellegrini,69,Juventus,20,2100000
6602,M. Fernández,69,Audax Italiano,30,850000
5662,M. Barrow,69,Atalanta,20,2300000
6046,M. Duffy,69,Dundalk,24,1300000
6060,M. Gómez,69,Rionegro Águilas,25,1300000
6061,J. Murillo,69,Independiente Medellín,25,1200000
5914,E. López,69,Guadalajara,24,1400000
5987,S. Gustafson,69,Torino,24,1300000
5990,Alberto,69,CD Tenerife,26,1200000
5962,J. Williams,69,Charlton Athletic,25,1400000
6009,R. Ibarra,69,Pachuca,24,1400000
5980,M. Sarr,69,Charlton Athletic,25,1200000
5959,J. Rodríguez,69,Defensa y Justicia,25,1200000
5932,C. Rodríguez,69,Deportivo Cali,25,1400000
5984,R. González,69,Club América,25,1300000
7321,R. Salinas,68,Puebla FC,31,775000
7294,J. Rojas,68,CD Huachipato,36,180000
7355,T. Smith,68,Colorado Rapids,29,750000
7370,E. Hernández,68,Pachuca,32,550000
7362,M. Pérez,68,Cúcuta Deportivo,34,450000
7181,I. González,68,CD Palestino,29,725000
7209,Bastos,68,Extremadura UD,27,900000
7206,F. Müller,68,SV Sandhausen,26,1100000
7280,D. Gray,68,Hibernian,31,650000
7246,S. Holmén,68,IF Elfsborg,35,375000
7587,E. Hernández,68,Envigado FC,33,475000
7605,M. Barbieri,68,Deportes Iquique,28,900000
7553,J. Hernández,68,Cúcuta Deportivo,33,425000
7533,J. López,68,Paris FC,27,950000
7684,J. Rodríguez,68,FC Botoşani,29,850000
7622,J. Pérez,68,Atlético Bucaramanga,30,850000
7456,M. Wittek,68,SV Darmstadt 98,30,725000
7476,J. Williams,68,Columbus Crew SC,31,675000
7448,Serginho,68,Matsumoto Yamaga,28,900000
7386,D. Hernández,68,CD Tenerife,33,475000
7431,D. Ward,68,Cardiff City,28,925000
7524,M. Herrera,68,Club León,30,725000
7534,R. Rodríguez,68,Newell's Old Boys,31,675000
7490,M. Smith,68,Millwall,30,875000
6761,L. Krejčí,68,Sparta Praha,20,1300000
6854,S. Mosquera,68,Deportes Tolima,25,1100000
6862,J. Silva,68,Club Tijuana,24,1100000
6878,D. Lemos,68,Once Caldas,24,1200000
6835,M. Koné,68,SG Dynamo Dresden,22,1300000
6679,G. Ferrari,68,San Lorenzo de Almagro,22,1500000
6674,J. Angulo,68,Club Atlas,21,1500000
7645,Y. Mutō,68,Urawa Red Diamonds,30,875000
6631,L. Kelly,68,Bournemouth,20,1800000
6740,M. Pedersen,68,FC Augsburg,22,1200000
6689,J. Arias,68,Patriotas Boyacá FC,21,1600000
7056,Jairo,68,Girona FC,25,1100000
7036,J. Gómez,68,Querétaro,25,1100000
7034,R. James,68,Doncaster Rovers,25,975000
7038,D. Moreno,68,Independiente Medellín,27,975000
6890,E. Castillo,68,Santos Laguna,24,1200000
6937,M. James,68,FC Midtjylland,25,1100000
6861,L. Kelly,68,Feyenoord,23,1200000
6858,J. Fernández,68,Newell's Old Boys,24,1200000
7008,V. Berisha,68,SK Brann,25,1100000
6970,Caro,68,Albacete BP,26,1000000
6963,Neto,68,América de Cali,26,850000
6969,A. Correa,68,La Equidad,25,1000000
8738,Paulinho,67,Matsumoto Yamaga,30,625000
7713,Miranda,67,FC Barcelona,19,1500000
7707,S. Sosa,67,River Plate,20,1600000
7778,M. Andersen,67,FC Nordsjælland,20,1300000
7756,M. Gómez,67,Gimnasia y Esgrima La Plata,20,1400000
7787,L. Suárez,67,Real Zaragoza,21,1300000
7811,L. Thomas,67,Barnsley,20,1200000
7839,João Afonso,67,Gil Vicente FC,24,1100000
7799,L. Kelly,67,Queens Park Rangers,23,975000
7814,H. Kane,67,Liverpool,20,1200000
7812,Marlon,67,Boavista FC,22,1100000
7846,J. Gómez,67,Junior FC,23,1100000
7907,C. González,67,CD Mirandés,22,1000000
7935,J. McCarthy,67,Millwall,23,950000
7940,D. Rodríguez,67,Once Caldas,24,1100000
7956,O. Duarte,67,Atlético Huila,23,1100000
8013,A. Ioniță,67,Universitatea Craiova,24,1000000
8007,M. Thiam,67,Barnsley,24,1000000
8064,M. Diagne,67,Sporting de Charleroi,25,900000
8055,C. Rodríguez,67,CD Everton de Viña del Mar,24,900000
8054,J. Martínez,67,Millonarios FC,25,750000
8106,Rômulo,67,Portimonense SC,23,925000
8125,L. Cabrera,67,Audax Italiano,25,900000
8135,L. López,67,Club América,25,975000
8150,T. Müller,67,1. FC Magdeburg,24,900000
8222,D. Schmidt,67,Sint-Truidense VV,27,675000
8183,Lucas,67,FC Luzern,26,850000
8242,J. Lowe,67,Bolton Wanderers,27,800000
8200,A. Ba,67,AJ Auxerre,25,850000
8269,A. Castro,67,Deportes Tolima,25,925000
8267,E. Boateng,67,DC United,25,925000
8285,M. Smith,67,Rotherham United,27,900000
8278,S. Camara,67,Le Havre AC,26,825000
8323,D. Torres,67,Audax Italiano,26,775000
8330,A. Rodríguez,67,Envigado FC,26,900000
8327,J. Pereira,67,Unión Magdalena,26,900000
8355,B. Jones,67,Rotherham United,32,475000
8416,D. Furman,67,South Africa,31,725000
8379,G. Rodríguez,67,Puebla FC,34,270000
8376,P. Álvarez,67,Arsenal de Sarandí,35,220000
8404,R. López,67,Tiburones Rojos de Veracruz,32,575000
8426,J. Martínez,67,Monarcas Morelia,32,475000
8436,J. Jones,67,Wigan Athletic,30,525000
8453,C. Evans,67,Fleetwood Town,30,725000
8511,S. Moore,67,Sheffield United,29,550000
8544,J. Morris,67,Fleetwood Town,27,800000
8608,F. Rodríguez,67,Rionegro Águilas,32,500000
8611,J. Aguirre,67,Atlético Bucaramanga,32,600000
8638,C. Ramírez,67,Rionegro Águilas,31,575000
8605,E. Farias,67,CD Cobresal,30,625000
8600,A. Jovanović,67,Jeju United FC,29,650000
8633,J. Gómez,67,Unión Española,28,650000
8664,D. Gómez,67,Once Caldas,31,550000
8721,Vinícius,67,Hungary,29,725000
8733,F. Pereyra,67,CD Huachipato,30,625000
7697,J. Álvarez,67,River Plate,19,1600000
8724,P. Herrmann,67,SV Darmstadt 98,31,550000
8772,L. Traoré,66,Ajax,18,1300000
8775,M. Sylla,66,AS Monaco,19,1400000
8796,M. Camara,66,BSC Young Boys,21,1300000
8849,L. Díaz,66,Columbus Crew SC,20,1100000
8814,J. Dasilva,66,Brentford,20,1100000
8915,J. Moreno,66,Millonarios FC,22,900000
8877,C. Vargas,66,Club América,20,950000
8909,J. Rodríguez,66,Central Córdoba,23,1000000
8933,A. Rossi,66,Castellammare di Stabia,22,1000000
8932,J. Angulo,66,Club Necaxa,22,1000000
8949,André Sousa,66,Vitória de Setúbal,21,900000
8955,A. Rodríguez,66,Newell's Old Boys,23,1000000
9011,A. Al Khaibari,66,Al Nassr,22,875000
9009,R. Williams,66,Shrewsbury,20,875000
8970,C. Dawson,66,Sheffield Wednesday,23,725000
9006,G. Gómez,66,Racing Club,23,725000
9000,J. Ramírez,66,Atlético Nacional,21,950000
9071,E. Eze,66,SK Sturm Graz,22,925000
9089,S. Nicholson,66,Sporting de Charleroi,22,925000
9047,Erik,66,CD Aves,24,925000
9077,B. White,66,New York Red Bulls,23,925000
9098,J. Allen,66,Coventry City,24,875000
9113,R. González,66,CD Huachipato,24,875000
9140,M. Ødegaard,66,Sarpsborg 08 FF,26,750000
9128,S. Diarra,66,Gazişehir Gaziantep F.K.,24,875000
9186,A. Soto,66,Patriotas Boyacá FC,24,750000
9158,K. Pedersen,66,Aalborg BK,26,750000
9180,M. Frey,66,SV Sandhausen,23,775000
9246,J. Arias,66,FC Emmen,24,850000
9259,D. Schmidt,66,Club Atlético Colón,26,725000
9254,J. Aguirre,66,Atlético Bucaramanga,27,575000
9289,R. Williams,66,Portsmouth,25,800000
9347,J. García,66,Arsenal de Sarandí,26,825000
9308,João Pedro,66,CD Tondela,26,775000
9376,Fernando,66,UD Almería,29,550000
9337,Eduardo,66,Matsumoto Yamaga,26,725000
9336,K. Matsubara,66,Yokohama F. Marinos,26,700000
9393,J. Sánchez,66,Atlético de San Luis,26,775000
9392,E. Gyasi,66,Spezia,25,775000
9353,Manu García,66,SD Ponferradina,28,575000
9423,A. Donnarumma,66,Milan,28,550000
9387,C. Vargas,66,Atlético Bucaramanga,29,550000
9442,Fábio,66,CD Aves,29,525000
9488,M. Álvarez,66,Independiente,30,500000
9447,J. Correa,66,Alianza Petrolera,26,775000
9479,D. Vega,66,Vålerenga Fotball,26,750000
9508,G. Evans,66,Portsmouth,31,575000
9524,A. Grant,66,Shrewsbury,32,425000
9554,J. Horn,66,Sarpsborg 08 FF,32,425000
9540,L. López,66,Tiburones Rojos de Veracruz,35,200000
9543,Juan Carlos,66,CD Numancia,31,425000
9591,M. Baudry,66,Swindon Town,31,475000
9647,Ricardinho,66,Wisła Płock,29,650000
9679,R. Torres,66,Independiente Santa Fe,27,675000
9643,Lee Jae Sung,66,Incheon United FC,30,525000
9642,Y. Endo,66,Kashima Antlers,31,575000
9778,B. García,66,Cúcuta Deportivo,32,425000
9738,Rafinha,66,HJK Helsinki,37,130000
9755,M. Salem,66,Al Shabab,33,300000
9769,A. Sánchez,66,Atlético Tucumán,32,400000
9790,E. Godoy,66,CD Cobresal,32,425000
9843,A. Keita,66,Östersunds FK,32,400000
10958,J. Clarke,65,Walsall,29,450000
10954,J. García,65,La Equidad,30,450000
9957,S. Sosa,65,AD Alcorcón,19,1200000
9977,A. Ba,65,FC Nantes,20,1000000
9992,Álvaro,65,SD Huesca,21,775000
10037,A. Vlad,65,FCSB (Steaua),20,750000
10058,J. Pérez,65,Los Angeles FC,21,875000
10098,J. Williams,65,Rochdale,23,750000
10087,Seoane,65,SD Huesca,22,850000
10109,A. Acosta,65,Puebla FC,22,825000
10108,E. Valencia,65,Cúcuta Deportivo,22,825000
10105,M. Andersen,65,Barnsley,21,775000
10120,R. González,65,Unión Española,23,825000
10133,M. García,65,Once Caldas,20,850000
10158,D. Rodríguez,65,Newell's Old Boys,23,775000
10174,R. Williams,65,Exeter City,22,800000
10168,J. Ward,65,Peterborough United,23,800000
10189,J. Hayes,65,FC Dallas,24,725000
10188,Wellington,65,Gil Vicente FC,24,625000
10209,J. Willis,65,Sunderland,24,675000
10214,Héctor,65,CF Fuenlabrada,23,775000
10279,M. Diaby,65,FC Paços de Ferreira,22,700000
10338,A. Traoré,65,FC Metz,24,750000
10329,A. Romero,65,Crotone,23,725000
10397,M. Nalepa,65,Arka Gdynia,24,700000
10427,A. Kamara,65,Randers FC,25,700000
10451,Mateus,65,Yokohama F. Marinos,24,700000
10450,J. Campbell,65,Seattle Sounders FC,26,625000
10459,P. Schmidt,65,1. FC Heidenheim 1846,25,700000
10475,D. Andrade,65,Santos Laguna,25,600000
10512,Castro,65,CD Lugo,24,700000
10539,Y. Suzuki,65,Oita Trinita,26,600000
10533,J. Hernández,65,Audax Italiano,26,675000
10557,R. Edwards,65,Blackpool,25,600000
10577,A. Öztürk,65,Sunderland,26,575000
10593,J. González,65,Club Necaxa,27,525000
10626,Bruno,65,Gil Vicente FC,25,450000
10615,J. Riley,65,Plymouth Argyle,27,525000
10643,Pablo,65,Santa Clara,26,625000
10636,D. González,65,Unión Magdalena,29,500000
10634,E. Pérez,65,FC Juárez,26,650000
10656,K. Nakamura,65,Shimizu S-Pulse,26,625000
10686,M. Roman,65,FCSB (Steaua),34,270000
10683,S. Brown,65,Port Vale,34,240000
10719,J. Brown,65,Coventry City,30,425000
10727,Aitor,65,Extremadura UD,32,325000
10724,M. Yıldırım,65,Yeni Malatyaspor,32,350000
10783,M. Pedersen,65,SønderjyskE,29,450000
10779,C. Gutiérrez,65,Tiburones Rojos de Veracruz,29,450000
10849,R. Riski,65,SKN St. Pölten,27,575000
10848,K. Larsen,65,Sarpsborg 08 FF,27,575000
10844,D. Tadić,65,TSV Hartberg,29,550000
10866,J. Valencia,65,Central Córdoba,27,575000
10876,J. Müller,65,SpVgg Unterhaching,29,525000
10875,A. N'Diaye,65,Clermont Foot 63,28,550000
10907,S. Romero,65,Atlético Bucaramanga,30,525000
10905,F. Castillo,65,Jaguares de Córdoba,29,450000
10921,L. Nielsen,65,Lyngby BK,32,350000
11015,M. Fernández,65,FC Juárez,30,500000
10992,F. Torres,65,Audax Italiano,30,450000
12157,M. Đurić,64,Central Coast Mariners,31,375000
12129,J. Pérez,64,Atlético Huila,30,350000
12143,J. Castro,64,Atlético de San Luis,27,475000
11050,D. Pérez,64,CD Huachipato,19,975000
11070,D. Lovren,64,Fortuna Düsseldorf,20,1000000
11078,Martín,64,Rayo Vallecano,19,900000
11096,João Moutinho,64,Orlando City SC,21,925000
11112,C. Tosun,64,Trabzonspor,19,825000
11141,O. Gonzalez,64,FC Chambly Oise,21,750000
11178,J. Jones,64,Coventry City,21,775000
11180,J. Lewis,64,Colorado Rapids,22,775000
11191,T. Müller,64,Hallescher FC,21,625000
11195,Murilo,64,Lokomotiv Moscow,22,700000
11201,D. Martínez,64,Defensa y Justicia,21,725000
11213,Jaume,64,CD Lugo,22,750000
11215,André Almeida,64,Vitória Guimarães,19,750000
11229,M. Gómez,64,Envigado FC,22,725000
11233,S. Hernández,64,Club Atlas,22,575000
11249,Miguel Ángel,64,CF Fuenlabrada,21,675000
11264,K. Watanabe,64,Yokohama F. Marinos,20,725000
11289,R. Tapia,64,Club Atlético Banfield,24,625000
11345,S. Coulibaly,64,AS Nancy Lorraine,23,600000
11361,M. Dembélé,64,AS Nancy Lorraine,22,675000
11371,E. Gutiérrez,64,Monterrey,23,600000
11373,J. Vargas,64,Deportes Tolima,24,600000
11375,A. Cruz,64,FC Cincinnati,23,675000
11380,S. Özcan,64,SC Preußen Münster,23,675000
11389,J. Brown,64,Colchester United,24,625000
11395,A. Bakayoko,64,Coventry City,23,650000
11414,A. Soumaoro,64,Livorno,22,575000
11428,J. Martínez,64,CF Fuenlabrada,24,650000
11443,R. Sánchez,64,Chicago Fire,25,450000
11448,M. Sarr,64,FC Carl Zeiss Jena,24,550000
11450,J. Wright,64,Doncaster Rovers,24,550000
11488,I. Sissoko,64,Chamois Niortais Football Club,23,625000
11490,A. Mendy,64,Racing Club de Lens,24,550000
11507,R. Edwards,64,Burton Albion,25,600000

In [ ]:
# Step: Fix release_clause_eur by replacing 0s and imputing missing values
release_col = 'release_clause_eur'

# Replace 0s with NaN
df_cleaned[release_col] = df_cleaned[release_col].replace(0, np.nan)

# Compute median and fill missing
release_median = df_cleaned[release_col].median()
df_cleaned[release_col] = df_cleaned[release_col].fillna(release_median)

# Output
print(f"✅ '{release_col}' parsed and 0s replaced.")
print(f"   {release_col} median used: €{int(release_median):,}")

✅ 'release_clause_eur' parsed and 0s replaced.
   release_clause_eur median used: €1,300,000

In [ ]:
# Count how many players have 'GK' listed in their player_positions
df_cleaned['player_positions'].str.contains("GK").sum()

np.int64(1925)

## Numerical imputation

In [ ]:
numeric_columns = df_cleaned.select_dtypes(include=['number']).columns.tolist()
print(numeric_columns)

['age', 'height_cm', 'weight_kg', 'overall', 'potential', 'value_eur', 'wage_eur', 'international_reputation', 'weak_foot', 'skill_moves', 'release_clause_eur', 'team_jersey_number', 'contract_valid_until', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed', 'gk_positioning', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'ls_score', 'st_score', 'rs_score', 'lw_score', 'lf_score', 'cf_score', 'rf_score', 'rw_score', 'lam_score', 'cam_score', 'ram_score', 'lm_score', 'lcm_score', 'cm_score', 'rcm_score', 'rm_score', 'lwb_score', 'ldm_score', 'cdm_score', 'rdm_score', 'rwb_score', 'lb_score', 'lcb_score', 'cb_score', 'rcb_score', 'rb_score', 'best_position_score']

In [ ]:
missing_over_1 = df_cleaned.isnull().sum()
missing_over_1 = missing_over_1[missing_over_1 > 1]

print("📌 Columns with more than 1 missing value:")
print(missing_over_1)

📌 Columns with more than 1 missing value:
team_position             232
team_jersey_number        232
joined                   1227
contract_valid_until      232
gk_diving               15429
gk_handling             15429
gk_kicking              15429
gk_reflexes             15429
gk_speed                15429
gk_positioning          15429
player_traits           10058
dtype: int64

In [ ]:
# Count how many players have 'GK' listed in their player_positions
df_cleaned['player_positions'].str.contains("GK").sum()

np.int64(1925)

# ✅ Columns to Impute Now:

In [ ]:
# Drop 'team_jersey_number' as it's not useful
df_cleaned.drop(columns=['team_jersey_number'], inplace=True)
print("🗑️ Dropped 'team_jersey_number' as it is not useful for modeling.")

# Fill missing 'team_position' with 'Unknown' as a placeholder
df_cleaned['team_position'].fillna('Unknown', inplace=True)

# Fill missing 'joined' with the mode (most frequent joining date)
joined_mode = df_cleaned['joined'].mode().iloc[0]
df_cleaned['joined'].fillna(joined_mode, inplace=True)

# Fill missing 'contract_valid_until' with the mode (most frequent year)
contract_mode = df_cleaned['contract_valid_until'].mode().iloc[0]
df_cleaned['contract_valid_until'].fillna(contract_mode, inplace=True)

# Fill missing 'player_traits' with 'None'
df_cleaned['player_traits'].fillna('None', inplace=True)

print("✅ Imputed missing values:")
print(f"   - 'team_position' filled with 'Unknown'")
print(f"   - 'joined' filled with mode: {joined_mode}")
print(f"   - 'contract_valid_until' filled with mode: {contract_mode}")
print(f"   - 'player_traits' filled with 'None'")

🗑️ Dropped 'team_jersey_number' as it is not useful for modeling.
✅ Imputed missing values:
   - 'team_position' filled with 'Unknown'
   - 'joined' filled with mode: 2019-07-01
   - 'contract_valid_until' filled with mode: 2020.0
   - 'player_traits' filled with 'None'

/tmp/ipython-input-237-395030360.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['team_position'].fillna('Unknown', inplace=True)
/tmp/ipython-input-237-395030360.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['joined'].fillna(joined_mode, inplace=True)
/tmp/ipython-input-237-395030360.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['contract_valid_until'].fillna(contract_mode, inplace=True)
/tmp/ipython-input-237-395030360.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['player_traits'].fillna('None', inplace=True)

## 🧤 Handling Goalkeeper-Specific Stats (gk_* Columns)
#### Objective: Ensure that goalkeeper-specific stats are meaningful and not misleading for outfield players.

In [ ]:

# 🔹 List of goalkeeper-specific columns
gk_cols = ['gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed', 'gk_positioning']

# 🔹 Replace NaNs in goalkeeper columns with 0
df_cleaned[gk_cols] = df_cleaned[gk_cols].fillna(0)

# ✅ Output summary
print("✅ Missing values in goalkeeper columns replaced with 0:")
print(f"   GK columns: {gk_cols}")

✅ Missing values in goalkeeper columns replaced with 0:
   GK columns: ['gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed', 'gk_positioning']

In [ ]:
# Show columns with missing values and their counts
missing_cols = df_cleaned.isnull().sum()
missing_cols = missing_cols[missing_cols > 0]

print("📌 Columns with missing values:")
print(missing_cols.sort_values(ascending=False))

📌 Columns with missing values:
Series([], dtype: int64)

#🔍  Final Check of the duplicates
 Possible Additional Duplicate Checks (Recommended):

In [ ]:
# 1. Check for duplicates by player name + club
dup_name_club = df_cleaned[df_cleaned.duplicated(subset=['short_name', 'club'], keep=False)]
print(f"🔁 Duplicates by short_name + club: {len(dup_name_club)}")
display(dup_name_club.head(3))

# 2. Drop exact full row duplicates (if any)
before = df_cleaned.shape[0]
df_cleaned.drop_duplicates(inplace=True)
after = df_cleaned.shape[0]
print(f"🧹 Dropped {before - after} exact duplicate rows.")

# 3. (Optional) Drop one record per short_name+club duplicate (if needed)
# Uncomment this line if you decide to keep only one entry per player+club
# df_cleaned.drop_duplicates(subset=['short_name', 'club'], keep='first', inplace=True)

🔁 Duplicates by short_name + club: 0

Empty DataFrame
Columns: [short_name, age, height_cm, weight_kg, nationality, club, overall, potential, value_eur, wage_eur, player_positions, preferred_foot, international_reputation, weak_foot, skill_moves, work_rate, body_type, real_face, release_clause_eur, team_position, joined, contract_valid_until, pace, shooting, passing, dribbling, defending, physic, gk_diving, gk_handling, gk_kicking, gk_reflexes, gk_speed, gk_positioning, player_traits, attacking_crossing, attacking_finishing, attacking_heading_accuracy, attacking_short_passing, attacking_volleys, skill_dribbling, skill_curve, skill_fk_accuracy, skill_long_passing, skill_ball_control, movement_acceleration, movement_sprint_speed, movement_agility, movement_reactions, movement_balance, power_shot_power, power_jumping, power_stamina, power_strength, power_long_shots, mentality_aggression, mentality_interceptions, mentality_positioning, mentality_vision, mentality_penalties, mentality_composure, defending_marking, defending_standing_tackle, defending_sliding_tackle, goalkeeping_diving, goalkeeping_handling, goalkeeping_kicking, goalkeeping_positioning, goalkeeping_reflexes, ls_score, st_score, rs_score, lw_score, lf_score, cf_score, rf_score, rw_score, lam_score, cam_score, ram_score, lm_score, lcm_score, cm_score, rcm_score, rm_score, lwb_score, ldm_score, cdm_score, rdm_score, rwb_score, lb_score, lcb_score, cb_score, rcb_score, rb_score, best_position, best_position_score]
Index: []

[0 rows x 97 columns]

🧹 Dropped 0 exact duplicate rows.

✅ Cleaned messy columns
✅ Parsed positional ratings
✅ Removed duplicates
✅ Handled missing values (numeric & categorical)
✅ GK stats carefully separated and treated
✅ Final dataset is clean, consistent, and analysis-ready.

In [ ]:
# Count how many players have 'GK' listed in their player_positions
df_cleaned['player_positions'].str.contains("GK").sum()

np.int64(1925)

In [ ]:
# # Save the cleaned DataFrame to a CSV file
# df_cleaned.to_csv("fifa20_cleaned_final.csv", index=False)

# # Download it (works in Colab)
# from google.colab import files
# files.download("fifa20_cleaned_final.csv")

In [ ]:
# Count how many players have 'GK' listed in their player_positions
df_cleaned['player_positions'].str.contains("GK").sum()

np.int64(1925)

In [ ]:
df_cleaned['best_position'].value_counts()

best_position
lcb    8165
ls     5001
lw     2017
lb      762
lf      441
lam     349
ldm     316
lcm     181
lwb     114
lm        8
Name: count, dtype: int64

In [ ]:
missing_over_1 = df_cleaned.isnull().sum()
missing_over_1 = missing_over_1[missing_over_1 > 1]

print("📌 Columns with more than 1 missing value:")
print(missing_over_1)

📌 Columns with more than 1 missing value:
Series([], dtype: int64)

In [ ]:
# Save the cleaned DataFrame to a CSV file
df_cleaned.to_csv("fifa20_final_gksave.csv", index=False)

# If you're using Google Colab and want to download it to your system:
from google.colab import files
files.download("fifa20_final_gksave.csv")

In [ ]:
# ✅ FINAL DATA CLEANING VALIDATION SUITE

# 🔹 Define GK columns
gk_cols = ['gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed', 'gk_positioning']

print("🔍 Running final validation tests...\n")

# 1. ✅ MISSING VALUES CHECK
missing_cols = df_cleaned.columns[df_cleaned.isnull().any()]
print("📌 Columns with missing values:", missing_cols.tolist())
print(f"🔍 Total missing cells: {df_cleaned.isnull().sum().sum()}\n")

# 2. ✅ DUPLICATES CHECK
duplicate_rows = df_cleaned.duplicated().sum()
print(f"🧾 Duplicate rows: {duplicate_rows}")

if 'short_name' in df_cleaned.columns and 'club' in df_cleaned.columns:
    name_club_dupes = df_cleaned.duplicated(subset=['short_name', 'club']).sum()
    print(f"👥 Duplicates by short_name + club: {name_club_dupes}\n")

# 3. ✅ VALUE CONSISTENCY CHECKS
age_outliers = df_cleaned[(df_cleaned['age'] < 15) | (df_cleaned['age'] > 50)]
print(f"⚠️ Players with unrealistic age (<15 or >50): {age_outliers.shape[0]}")

bad_rating_rows = df_cleaned[(df_cleaned['overall'] > 99) | (df_cleaned['potential'] > 99)]
print(f"⚠️ Players with rating issues (overall/potential >99): {bad_rating_rows.shape[0]}")

valid_positions = ['GK', 'ST', 'CF', 'LW', 'RW', 'CAM', 'CM', 'CDM', 'CB', 'LB', 'RB',
                   'LAM', 'RAM', 'LCM', 'RCM', 'LM', 'RM', 'LWB', 'RWB', 'LS', 'RS', 'LF', 'RF', 'RCB', 'LCB']
invalid_positions = df_cleaned[~df_cleaned['best_position'].isin(valid_positions)]
print(f"❌ Invalid best_position values: {invalid_positions.shape[0]}\n")

# 4. ✅ ECONOMIC COLUMNS SANITY CHECK
econ_cols = ['value_eur', 'wage_eur', 'release_clause_eur']
for col in econ_cols:
    neg_vals = df_cleaned[df_cleaned[col] < 0].shape[0]
    print(f"⚠️ Negative values in {col}: {neg_vals}")
print()

# 5. ✅ GK STATS CHECK FOR NON-GKs
non_gks = df_cleaned[df_cleaned['best_position'] != 'GK']
non_gk_violations = non_gks[gk_cols].sum().sum()
print(f"🔒 Non-GKs with non-zero GK stats: {non_gk_violations}")

print("\n✅ Validation complete.")

🔍 Running final validation tests...

📌 Columns with missing values: []
🔍 Total missing cells: 0

🧾 Duplicate rows: 0
👥 Duplicates by short_name + club: 0

⚠️ Players with unrealistic age (<15 or >50): 0
⚠️ Players with rating issues (overall/potential >99): 0
❌ Invalid best_position values: 17354

⚠️ Negative values in value_eur: 0
⚠️ Negative values in wage_eur: 0
⚠️ Negative values in release_clause_eur: 0

🔒 Non-GKs with non-zero GK stats: 690389.0

✅ Validation complete.

# Body type

In [ ]:
df_cleaned['body_type'].unique()

array(['Messi', 'C. Ronaldo', 'Neymar', 'Normal', 'Lean',
       'PLAYER_BODY_TYPE_25', 'Stocky', 'Courtois', 'Shaqiri',
       'Akinfenwa'], dtype=object)

In [ ]:
# Define valid body types
valid_body_types = ['Normal', 'Lean', 'Stocky']

# Replace uncommon or animation-based body types with 'Normal'
df_cleaned['body_type'] = df_cleaned['body_type'].apply(lambda x: x if x in valid_body_types else 'Normal')

# Output unique values after cleaning
print("✅ Cleaned 'body_type' values:")
print(df_cleaned['body_type'].value_counts())

✅ Cleaned 'body_type' values:
body_type
Normal    10251
Lean       6156
Stocky      947
Name: count, dtype: int64

# Player Position Handeling

In [ ]:
# ✅ STEP 1: Extract Primary Position (first listed)
df_cleaned['primary_position'] = df_cleaned['player_positions'].str.split(',').str[0].str.strip()

# ✅ STEP 2: Create Number of Positions Played
df_cleaned['n_positions'] = df_cleaned['player_positions'].str.split(',').apply(len)

# ✅ STEP 3: Keep best_position as is (already present)

# ✅ STEP 4 (Optional): Map Positions into Broad Role Groups
position_map = {
    'GK': 'Goalkeeper',
    'CB': 'Defender', 'RB': 'Defender', 'LB': 'Defender', 'RCB': 'Defender', 'LCB': 'Defender',
    'RWB': 'Defender', 'LWB': 'Defender',
    'CDM': 'Midfielder', 'CM': 'Midfielder', 'CAM': 'Midfielder', 'LM': 'Midfielder', 'RM': 'Midfielder',
    'RCM': 'Midfielder', 'LCM': 'Midfielder', 'RAM': 'Midfielder', 'LAM': 'Midfielder', 'RDM': 'Midfielder', 'LDM': 'Midfielder',
    'RW': 'Attacker', 'LW': 'Attacker', 'CF': 'Attacker', 'ST': 'Attacker',
    'LS': 'Attacker', 'RS': 'Attacker', 'RF': 'Attacker', 'LF': 'Attacker'
}

df_cleaned['role_group'] = df_cleaned['primary_position'].map(position_map)

In [ ]:
df_cleaned.shape

(17354, 100)

# preferred_foot

In [ ]:
df_cleaned['preferred_foot'].value_counts(dropna=False)

preferred_foot
Right    13241
Left      4113
Name: count, dtype: int64

In [ ]:
df_cleaned['work_rate'].value_counts(dropna=False)

work_rate
Medium/Medium    9317
High/Medium      3079
Medium/High      1641
High/High         948
Medium/Low        852
High/Low          653
Low/Medium        438
Low/High          394
Low/Low            32
Name: count, dtype: int64

In [ ]:
# 🔹 Split 'work_rate' into two separate columns
df_cleaned[['attacking_work_rate', 'defensive_work_rate']] = df_cleaned['work_rate'].str.split('/', expand=True)

# 🔹 Drop original 'work_rate' column
df_cleaned.drop(columns='work_rate', inplace=True)

# 🔹 Define encoding map
work_rate_map = {'Low': 0, 'Medium': 1, 'High': 2}

# 🔹 Convert both new columns to numerical values
df_cleaned['attacking_work_rate'] = df_cleaned['attacking_work_rate'].map(work_rate_map)
df_cleaned['defensive_work_rate'] = df_cleaned['defensive_work_rate'].map(work_rate_map)

# ✅ Output check
print("✅ work_rate split and encoded successfully.")
print(df_cleaned[['attacking_work_rate', 'defensive_work_rate']].head())

✅ work_rate split and encoded successfully.
   attacking_work_rate  defensive_work_rate
0                    1                    0
1                    2                    0
2                    2                    1
3                    1                    1
4                    2                    1

In [ ]:
df_cleaned.shape

(17354, 101)

In [ ]:
df_cleaned['real_face'].value_counts(dropna=False)

real_face
No     15420
Yes     1934
Name: count, dtype: int64

In [ ]:
df_cleaned.drop(columns=['real_face'], inplace=True)

In [ ]:
# # Save the DataFrame to CSV
# df_cleaned.to_csv("fifa20_finalptag.csv", index=False)

# # Download the file
# from google.colab import files
# files.download("fifa20_finalptag.csv")

In [ ]:
df_cleaned.columns.to_list()

['short_name',
 'age',
 'height_cm',
 'weight_kg',
 'nationality',
 'club',
 'overall',
 'potential',
 'value_eur',
 'wage_eur',
 'player_positions',
 'preferred_foot',
 'international_reputation',
 'weak_foot',
 'skill_moves',
 'body_type',
 'release_clause_eur',
 'team_position',
 'joined',
 'contract_valid_until',
 'pace',
 'shooting',
 'passing',
 'dribbling',
 'defending',
 'physic',
 'gk_diving',
 'gk_handling',
 'gk_kicking',
 'gk_reflexes',
 'gk_speed',
 'gk_positioning',
 'player_traits',
 'attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control',
 'movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance',
 'power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots',
 'mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure',
 'defending_marking',
 'defending_standing_tackle',
 'defending_sliding_tackle',
 'goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'ls_score',
 'st_score',
 'rs_score',
 'lw_score',
 'lf_score',
 'cf_score',
 'rf_score',
 'rw_score',
 'lam_score',
 'cam_score',
 'ram_score',
 'lm_score',
 'lcm_score',
 'cm_score',
 'rcm_score',
 'rm_score',
 'lwb_score',
 'ldm_score',
 'cdm_score',
 'rdm_score',
 'rwb_score',
 'lb_score',
 'lcb_score',
 'cb_score',
 'rcb_score',
 'rb_score',
 'best_position',
 'best_position_score',
 'primary_position',
 'n_positions',
 'role_group',
 'attacking_work_rate',
 'defensive_work_rate']

In [ ]:
# 1️⃣ Extract the primary position (first position before any comma)
df_cleaned['primary_position'] = df_cleaned['player_positions'].str.split(',').str[0].str.strip()

# 2️⃣ One-hot encode all positions (multi-hot encoding)
from sklearn.preprocessing import MultiLabelBinarizer

# Split and strip all player_positions into lists
positions_split = df_cleaned['player_positions'].str.split(',').apply(lambda x: [p.strip() for p in x])

# Create binary indicators for all positions
mlb = MultiLabelBinarizer()
position_dummies = pd.DataFrame(mlb.fit_transform(positions_split),
                                columns=mlb.classes_,
                                index=df_cleaned.index)

# 3️⃣ Combine with the original dataframe
df_cleaned = pd.concat([df_cleaned, position_dummies], axis=1)

# 4️⃣ (Optional) Drop the original player_positions column
# df_cleaned.drop(columns=['player_positions'], inplace=True)

# ✅ Summary
print(f"✅ Added 'primary_position' column and {position_dummies.shape[1]} position indicator columns.")
print("🎯 Top 5 rows:")
print(df_cleaned[['primary_position'] + list(position_dummies.columns)].head())

✅ Added 'primary_position' column and 15 position indicator columns.
🎯 Top 5 rows:
  primary_position  CAM  CB  CDM  CF  CM  GK  LB  LM  LW  LWB  RB  RM  RW  \
0               RW    0   0    0   1   0   0   0   0   0    0   0   0   1
1               ST    0   0    0   0   0   0   0   0   1    0   0   0   0
2               LW    1   0    0   0   0   0   0   0   1    0   0   0   0
3               GK    0   0    0   0   0   1   0   0   0    0   0   0   0
4               LW    0   0    0   1   0   0   0   0   1    0   0   0   0

   RWB  ST
0    0   1
1    0   1
2    0   0
3    0   0
4    0   0

In [ ]:
# 4️⃣ (Optional) Drop the original player_positions column
df_cleaned.drop(columns=['player_positions'], inplace=True)

In [ ]:
df_cleaned.shape

(17354, 114)

In [ ]:
df_cleaned['joined'].info()# df_cleaned['real_face'].describe

<class 'pandas.core.series.Series'>
RangeIndex: 17354 entries, 0 to 17353
Series name: joined
Non-Null Count  Dtype
--------------  -----
17354 non-null  object
dtypes: object(1)
memory usage: 135.7+ KB

In [ ]:
# Step 1: Convert to datetime
df_cleaned['joined'] = pd.to_datetime(df_cleaned['joined'], errors='coerce')

# Step 2: Extract year
df_cleaned['joined'] = df_cleaned['joined'].dt.year

# Calcualte tenure Years unsind joined and  contract_valis_until columns

In [ ]:
# ✅ Calculate tenure in years directly from year columns
df_cleaned['tenure_years'] = df_cleaned['contract_valid_until'] - df_cleaned['joined']

# ✅ Drop the original year columns
df_cleaned.drop(['joined', 'contract_valid_until'], axis=1, inplace=True)

# ✅ Optional check
print("🎯 Tenure calculation complete.")
print(df_cleaned['tenure_years'].describe())

🎯 Tenure calculation complete.
count    17354.000000
mean         3.724617
std          2.420296
min          0.000000
25%          2.000000
50%          3.000000
75%          5.000000
max         26.000000
Name: tenure_years, dtype: float64

#💰 Log-Transformed Financial Features
##🧾 Description:
To reduce skewness and handle the wide range of monetary values in the FIFA 20 dataset, we applied natural logarithmic transformation (log1p, i.e., log(x + 1)) to the following financial features:

#value_eur → log_value_eur
Represents the market value of the player in euros.
The transformed column captures relative value differences more effectively by compressing large ranges and making the distribution more normal-like.

#wage_eur → log_wage_eur
Represents the player's weekly wage in euros.
Log transformation reduces the extreme imbalance caused by a few highly paid players.

#release_clause_eur → log_release_clause_eur
Represents the release clause amount (minimum transfer fee) in euros.
The transformation helps in dealing with large variations and zero values.

#✅ Why it's useful:
Handles outliers and skewed distributions.

Improves performance of regression and distance-based models.

Retains interpretability via the log scale.

In [ ]:
import numpy as np

# Log-transform value, wage, and release clause with +1 to handle 0 values
df_cleaned['log_value_eur'] = np.log1p(df_cleaned['value_eur'])
df_cleaned['log_wage_eur'] = np.log1p(df_cleaned['wage_eur'])
df_cleaned['log_release_clause_eur'] = np.log1p(df_cleaned['release_clause_eur'])

# ✅ Optional: check skew before and after (optional sanity check)
print("Skewness before log:")
print(df_cleaned[['value_eur', 'wage_eur', 'release_clause_eur']].skew())

print("\nSkewness after log:")
print(df_cleaned[['log_value_eur', 'log_wage_eur', 'log_release_clause_eur']].skew())

Skewness before log:
value_eur             6.314159
wage_eur              7.691528
release_clause_eur    6.575909
dtype: float64

Skewness after log:
log_value_eur             0.402578
log_wage_eur              0.754918
log_release_clause_eur    0.487594
dtype: float64

In [ ]:
df_cleaned.columns.to_list()

['short_name',
 'age',
 'height_cm',
 'weight_kg',
 'nationality',
 'club',
 'overall',
 'potential',
 'value_eur',
 'wage_eur',
 'preferred_foot',
 'international_reputation',
 'weak_foot',
 'skill_moves',
 'body_type',
 'release_clause_eur',
 'team_position',
 'pace',
 'shooting',
 'passing',
 'dribbling',
 'defending',
 'physic',
 'gk_diving',
 'gk_handling',
 'gk_kicking',
 'gk_reflexes',
 'gk_speed',
 'gk_positioning',
 'player_traits',
 'attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control',
 'movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance',
 'power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots',
 'mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure',
 'defending_marking',
 'defending_standing_tackle',
 'defending_sliding_tackle',
 'goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'ls_score',
 'st_score',
 'rs_score',
 'lw_score',
 'lf_score',
 'cf_score',
 'rf_score',
 'rw_score',
 'lam_score',
 'cam_score',
 'ram_score',
 'lm_score',
 'lcm_score',
 'cm_score',
 'rcm_score',
 'rm_score',
 'lwb_score',
 'ldm_score',
 'cdm_score',
 'rdm_score',
 'rwb_score',
 'lb_score',
 'lcb_score',
 'cb_score',
 'rcb_score',
 'rb_score',
 'best_position',
 'best_position_score',
 'primary_position',
 'n_positions',
 'role_group',
 'attacking_work_rate',
 'defensive_work_rate',
 'CAM',
 'CB',
 'CDM',
 'CF',
 'CM',
 'GK',
 'LB',
 'LM',
 'LW',
 'LWB',
 'RB',
 'RM',
 'RW',
 'RWB',
 'ST',
 'tenure_years',
 'log_value_eur',
 'log_wage_eur',
 'log_release_clause_eur']

In [ ]:
# Update best_position to "gk" where role_group is "Goalkeeper"
for index, row in df_cleaned.iterrows():
    if row['role_group'] == 'Goalkeeper':
        df.at[index, 'best_position'] = 'gk'

In [ ]:
from google.colab import files

# Save DataFrame to CSV
df_cleaned.to_csv("fifa20_feature.csv", index=False)

# Download the file
files.download("fifa20_feature.csv")

In [ ]:
df_cleaned.shape

(17354, 116)